### ISSUE TITLE
Question: Not all folders are visible

### ISSUE THREAD

**Issue by hugo-leij** [raonigabriel/web-terminal#2]
Hey,

I'm using a raspberry pi (64bit) and i love to have a webbased terminal so i can fix things on my phone if i'm on the road. 

I need to go into the pi user '/home/pi' but in the webbased terminal there is no pi folder, is there something with rights?

**Running docker:**
`docker run --rm -d -p 7681:7681 raonigabriel/web-terminal:latest`

**Webbased terminal**
```
root@372a126598ad:/$ ls
bin    dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
root@372a126598ad:/$ cd home/
root@372a126598ad:/home$ ls
root@372a126598ad:/home$ 
```

**Normal terminal**
```
pi@raspberrypi:/ $ ls
bin  boot  dev  etc  home  lib  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
pi@raspberrypi:/ $ cd home/
pi@raspberrypi:/home $ ls
pi
pi@raspberrypi:/home $
```

**Comment by raonigabriel** [comment]
I guess this is probably a missunderstaing of the concepts. Let me try to help:

When you launch this image on your pi, it will be running inside docker, as a container. So the web based shell you see ia not actually from  your pi, but from the container instead. 

The beauty of this thing is to isolate your pi os (maybe raspbian) from the internal container os  (alpine). So, if you want to access your pi's content from that container,  you need first to bind-mount it to the container. Take a look bellow, and search the web for the official docker docs regarding "volume mount ".

Original: # docker run --rm -d -p 7681:7681 raonigabriel/web-terminal:latest

Bind-mounting: # docker run --rm -d -v /home/pi:/home/pi -p 7681:7681 raonigabriel/web-terminal:latest

(See the -v there? That means "volume mount").
Note: keep in mind that this image comes with no security enforced nor password, so be carefull whenever exposing your pi over the internet like that).

**Comment by hugo-leij** [comment]
He @raonigabriel 

Thanks for your explanation! I'm a bit ashamed of myself because I have +25 docker containers running. Didn't think about the volume mount at all.

Security wise, I have a VPN with 2FA. Hopefully thats enough :-) 

Thnx!
